name: FastAPI-Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  train_pipeline:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Training model
          run: |
            python train.py